name: "Action test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v1

      - name: Set commit status
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success
          description: Status added to commit!
          url: https://github.com/pbrandone/create-status-action
          context: action test run
